### ISSUE TITLE
Figure out Install-Package experience

### ISSUE THREAD

**Issue by nikmd23** [avanderhoorn/Glimpse.Prototype#13]
What does the Glimpse v2 install experience look like? This issue is _not_ about nailing down names or actually creating all the packages, but rather represents a thought exercise that should solve:
1. How will users install Glimpse into their greenfield application?
2. How will Glimpse grow with users when they move to a multiple WFE environment?

To be considered, Agents, Server, Client(s), Storage & Extensions, both client & agent based.

**Comment by avanderhoorn** [comment]
The ~~current~~ proposed package structure is fairly granular. This has the benefit of facilitating a lot of code reuse/sharing, as well as a lot of facilitating a lot of different deployment models. 

### Base Structure

Its is built on the back of the following shared packages:
- _Glimpse.Common_: Anything that any package needs access too
- _Glimpse.Web.Common_: Anything that any package that is on a web stack would need
- _Glimpse.Agent.Common_: Anything that a .Net based agent would need regardless of environment
- _Glimpse.Server.Common_: Anything that any .Net based server would need regardless of environment
  - Probably not that useful in practice given that the server will always be a web server

Then when it starts coming to concrete implementations we have the following packages:
- **Agents**:
  - _Glimpse.Agent.Browser_: Browser agent host & base agent inspector, served from the below Host
  - _Glimpse.Agent.Web_: Web Agent Host & base agent inspector
    - _Glimpse.Agent.Mvc_: Mvc specific agent inspector, hosted from the Agent Host
    - _Glimpse.Agent.Ado_*: Ado specific agent inspector, hosted from the Agent Host
    - _Glimpse.Agent.Ef_*: EF specific agent inspector, hosted from the Agent Host
    - _Glimpse.Agent.Network_*: Network specific agent inspector, hosted from the Agent Host
  - _Glimpse.Agent.Connection.Http_: Connection agent strategy using Http connections for Agents
  - _Glimpse.Agent.Connection.Socket_: Connection agent strategy using Web Sockets for Agents
- **Server**:
  - _Glimpse.Server.Web_: Web Server & Service which coordinates storage and client access
    - _Glimpse.Storage.DocumentDb_: Data store strategy based on DocumentDB for Web Server 
    - _Glimpse.Storage.SqlServer_*: Data store strategy based on Sql Server for Web Server 
- **Clients**:
  - _Glimpse.Client.Web_: Web Client that acts as primary view, served from Web Server
  - _Glimpse.Client.Hud_*: Hud Client that acts as secondary view, served from Web Server
  - _Glimpse.Client.Web.Simple_: Simple Web Client used for testing msgs, served from Web Server

*Denotes packages that are not yet in existence

### Common Configurations

Many different configuration options are possible, but the two most common use cases pivot around whether one is in development  or production. During development, setup and configuration should be simple and easy to understand. When moving to production, due to the very nature of production and the different possible setups, configuration should be explicit and defined by the user.  

**Development**
This will most commonly be used during development or in single server server test environments, where persistent storage isn't needed. It would leverage the following components:
- _Agent & Server Machine_
  - Glimpse.Agent.Browser, Glimpse.Agent.Web, Glimpse.Agent.Mvc, Glimpse.Agent.Ado, Glimpse.Agent.Ef, Glimpse.Agent.Network, Glimpse.Server.Web (using inproc connection to server), Glimpse.Server.Web, Glimpse.Client.Web, Glimpse.Client.Hud

_Service Configuration_
The combination of packages and the agent and server running in proc on the one machine would result in a service configuration like the following:

``` C#
public void ConfigureServices(IServiceCollection services)
{
  services
    .AddGlimpse()
    .RunningAgentWeb()
    .WithAgentBrowser().WithAgentMvc().WithAgentAdo().WithAgentEf().WithAgentNetwork()
    .RunningServerWeb()
    .WithLocalAgent()
    .WithClientWeb().WithClientHud();
  //...
}
```

**Production**
This is used in cases where multiple servers are at play (hence the agent needs to run on multiple machines) and a central Glimpse server is used to consolidate the collected data. It would leverage the following components:
- _Agent Machines_:
  - Glimpse.Agent.Browser, Glimpse.Agent.Web, Glimpse.Agent.Mvc, Glimpse.Agent.Ado, Glimpse.Agent.Ef, Glimpse.Agent.Network, _Glimpse.Agent.Connection.Socket_
- _Server Machine_:
  - Glimpse.Server.Web, _Glimpse.Storage.xyz_, Glimpse.Server.Web, Glimpse.Client.Web, Glimpse.Client.Hud

_Service Configuration_
The resulting package split needed to run the agent and server on different machines would result in a service configuration like the following:

``` c#
// Agent config
public void ConfigureServices(IServiceCollection services)
{
  services
    .AddGlimpse()
    .RunningAgentWeb()
    .WithAgentBrowser().WithAgentMvc().WithAgentAdo().WithAgentEf().WithAgentNetwork()
    .UsingSocketConnection()
  //...
}

// Server config
public void ConfigureServices(IServiceCollection services)
{
  services
    .AddGlimpse()
    .RunningServerWeb() 
    .WithClientWeb().WithClientHud()
    .UsingXyzForStorage();
  //...
}
```

### Meta Packages

Despite the fact that the package structure allows for a high degree of flexibility on the behalf of the user, for the most common use case (development), it requires a large amount of knowledge to get the various pieces to work together. "Meta" packages are commonly used to service the most common use cases for a project - as leveraged by [Microsoft.AspNet.Mvc](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNet.Mvc). Hence the following meta packages are being proposed:

**Glimpse.Development**/**Glimpse**
This package is targeted at simplifying the Development time use case above. By adding the one _Glimpse.Development_/_Glimpse_ package, it would bring in the following packages automatically:
- Glimpse.Agent.Browser, Glimpse.Agent.Web, Glimpse.Agent.Mvc, Glimpse.Agent.Ado, Glimpse.Agent.Ef, Glimpse.Agent.Network, Glimpse.Server.Web (using inproc connection to server), Glimpse.Server.Web, Glimpse.Client.Web, Glimpse.Client.Hud

_Service Configuration_
Further more, it would reduce the service configuration to the following:

``` C#
public void ConfigureServices(IServiceCollection services)
{
  services
  .AddGlimpseForDevelopment();

  // NOTE: `.AddGlimpseForDevelopment()` would be a wrapper around the following
  // services
  //     .AddGlimpse()
  //     .RunningAgentWeb()
  //         .WithAgentBrowser().WithAgentMvc().WithAgentAdo().WithAgentEf().WithAgentNetwork()
  //     .RunningServerWeb()
  //         .WithLocalAgent()
  //         .WithClientWeb().WithClientHud();
  //...
}
```

**Other**
Other meta packages could be considered but they could also result in confusion if over used. The other two that possibly make sense are:
- Glimpse.Agent & Glimpse.Server

These would wrap up the most common Agent and Server scenarios. Note, server is more difficult as in the Server case, a storage strategy is required to be setup by the user.

### Feedback

If you have any thoughts on the proposed package setup please let us know.

**Comment by nikmd23** [comment]
I have a few questions:

> - Glimpse.Web.Common: Anything that any package that is on a web stack would need

**Q) What's an example of something that would go in there?**
- _A) At the moment it adds HttpContext semantics onto our Context, as well as any shared config options. This could disappeared as some of the context refactorings occur._ 

> **Agents:**
> - Glimpse.Agent.Browser: Browser agent host & base agent inspector, served from the below Host
> 
> **Clients**:
> - Glimpse.Client.Web: Web Client that acts as primary view, served from Web Server
> - Glimpse.Client.Hud*: Hud Client that acts as secondary view, served from Web Server

**Q) Is it safe to assume that these won't be a NuGet package but rather an NPM, Bower or JSPM packages?**
- _A) No. The JS itself will be an NPM package, but the packages I'm referring to here are .Net packages that have the JS embedded and server it up via the Glimpse host. Allows us to be more consistent with versioning and not have to worry about a loose JS file being correctly found and embedded._

> - Glimpse.Agent.Connection.Http: Connection agent strategy using Http connections for Agents
> - Glimpse.Agent.Connection.Socket: Connection agent strategy using Web Sockets for Agents

**Q) Connections are tricky because there is a client side and a server side to each end. Some clients are JS based while others are .NET based. Perhaps it'd be good to elevate connections to their own section of the document? I think #22 covers all the combinations we'd support.**
- _A) Makes sense. At the moment, the server has the server side of these strategies all built into the box. This could be changed but I did it this way for simplicity._

_Note, it may make sense to loop back to this question once #22 is complete._

> **Server:**
> - Glimpse.Server.Web: Web Server & Service which coordinates storage and client access 

**Q) Is the idea that there would be more packages in this section to handle hosting the server? For example, how might deployment of the server to an Azure Web Site work?**
- _A) Possibly. Not 100% sure yet but it made sense given what could happen and the fact that we may have different server implementations. How much shared code there is between them I'm not sure_

> **Glimpse.Development/Glimpse**

**Q) I really like the idea of the development time meta-package just being called Glimpse. I wonder how that will play up with 1.X packages.**
- _A) Ya not sure... have to think about that. Trying to make discoverability easy..._

> _Service Configuration_

**Q) I appreciate you adding this detail in. I think we have some room for improvement on the configuration stuff, but that's not the purpose of this issue.**
- _A) Yep, just trying to show how the packages come together_

> **Other**
> Other meta packages could be considered but they could also result in confusion if over used. The other two that possibly make sense are:
> - Glimpse.Agent & Glimpse.Server

**Q) I think there is a good use case for at least something like `Glimpse.WebServer.Agent`. I'd see users graduate from `Glimpse.Development` to `Glimpse.WebServer.Agent` when they move to a webfarm.**
- _A) Yep agreed. Just need to work out a convention that conveys the difference between feature packages and these meta packages_

**Comment by avanderhoorn** [comment]
Ok updated the questions inline, seemed easier.

**Comment by avanderhoorn** [comment]
For what we need to workout at the moment, I'm going to close this off. Can reopen when we actually want to make further decisions
